name: CI
on:
  pull_request:
    branches: [main]
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: make fmt lint
      - run: make test
      - run: make build
